[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyperceive"
version = "0.2.0"
description = 'Importing and using Perceived Percept data in Python'
readme = "README.md"
requires-python = ">3.8"
license = {file = "LICENSE.txt"}
keywords = ["finger-tapping", "UPDRS", "Parkinsons disease ", "bradykinesia"]
authors = [
    { name = "Jeroen G.V. Habets" },
    { name = "Jennifer Kim Behnke" },
    { name = "Richard M. Köhler" },
    { name = "Arian Memarpouri" }
]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Programming Language :: Python",
  "Intended Audience :: Neurological, Movement Disorders, Researchers",
  "License :: OSI Approved :: MIT License"
]

[project.urls]
homepage = "https://github.com/jgvhabets/PyPerceive"
repository = "https://github.com/jgvhabets/PyPerceive"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]